spring:
  application:
    name: Employee-Management



  datasource:
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: rootuser99

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

    open-in-view: false

    logging:
      level:
        org.springframework.security: DEBUG

